# Generated by Django 4.2.3 on 2023-08-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimGame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='seller_quantity',
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
    ]
