# Generated by Django 4.2.3 on 2023-08-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimGame', '0002_remove_transaction_seller_quantity_delete_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cumulative_quantity_sum',
            field=models.IntegerField(default=0),
        ),
    ]
