# Generated by Django 4.2.3 on 2023-08-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimGame', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cumulative_quantity_bought',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cumulative_quantity_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.IntegerField(default=0)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SimGame.goods')),
            ],
        ),
    ]
