# Generated by Django 4.2.3 on 2023-08-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimGame', '0003_transaction_cumulative_quantity_bought_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cumulative_net_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
