# Generated by Django 4.2.3 on 2023-08-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimGame', '0004_transaction_cumulative_net_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cumulative_net_quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cumulative_quantity_bought',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cumulative_quantity_sold',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cumulative_quantity_sum',
            field=models.IntegerField(default=0),
        ),
    ]
