# Generated by Django 4.2.3 on 2023-08-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimGame', '0005_remove_transaction_cumulative_net_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cumulative_quantity_sum',
        ),
        migrations.AddField(
            model_name='goods',
            name='cumulative_demand',
            field=models.IntegerField(default=0),
        ),
    ]
