# Generated by Django 4.2.3 on 2023-08-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimGame', '0006_remove_transaction_cumulative_quantity_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='demand_change',
            field=models.IntegerField(default=0),
        ),
    ]
